config/routes.rb
Rails.application.routes.draw do

  root  to: 'entries#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  # User routes
  get '/users', to: 'users#index'
  post '/users', to: 'users#create'
  get '/signup', to: 'users#new'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  get '/users/:id', to: 'users#show', as: 'user'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  # City routes
  get '/cities', to: 'cities#index'
  post '/cities', to: 'cities#create'
  get '/cities/new', to: 'cities#new', as: 'new_city'
  get '/cities/:id/edit', to: 'cities#edit', as: 'edit_city'
  get '/cities/:id', to: 'cities#show', as: 'city_show'
  patch '/cities/:id', to: 'cities#update'
  delete '/cities/:id', to: 'cities#destroy'

  #Entry routes
  get '/entries', to: 'entries#index'
  post '/entries', to: 'entries#create'
  get '/entries/new', to: 'entries#new', as: 'new_entry'
  get '/entries/:id/edit', to: 'entries#edit', as: 'edit_entry'
  get '/entries/:id', to: 'entries#show', as: 'entry_show'
  patch '/entries/:id', to: 'entries#update', as: 'entry_update'
  delete '/entries/:id', to: 'entries#destroy', as: 'delete_entry'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  extend FriendlyId
	has_many :entries
	has_many :users, through: :entries

  friendly_id :name, use: :slugged
end

app/models/entry.rb
class Entry < ApplicationRecord
  extend FriendlyId
	belongs_to :user
  belongs_to :city


  friendly_id :title, use: :slugged
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, default_url: 'http://greentreesarborcareinc.com/wp-content/uploads/2014/01/image-placeholder.jpg'
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :city_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
	has_many :entries, dependent: :destroy
	has_many :cities, through: :entries

  friendly_id :first_name, use: :slugged

	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#" }, default_url: "http://www.dentalmarketing.ee/wp-content/uploads/2015/09/staff_placeholder.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	before_save { email.downcase! }
	validates :first_name, presence: true, length: {maximum: 50}
	validates :last_name, presence: true, length: {maximum: 50}
	validates :current_city, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

	has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/cities_controller.rb
  class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all
    render :index
  end

  def show
    render :show
  end

  def new
    @cities = City.new
    render :new
  end

  def create
    @city = City.create(city_params)
    redirect_to :index
  end

  def edit
    @city = City.friendly.find(city_params)
  end

  def update
    @city = City.find(city_params)
    @city.update_attributes(city_params)
    redirect_to :index
  end

  def destroy
    @city.destroy
    redirect_to :index
  end

  private

  def set_city
    @city = City.friendly.find(params[:id])
  end

  def city_params
    params.require(:city).permit(:name, :photo, :slug)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :logged_in?, only: [:create, :edit, :destroy]
  before_action :correct_user,   only: [ :edit, :destroy]

  def index
    @entries = Entry.paginate(page: params[:page], per_page: 12)
  end

  def show
    @entry = Entry.friendly.find(params[:id])
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = current_user.entries.build(entry_params)
    if @entry.save
      flash[:success] = "Entry created!"
      redirect_to root_url
    else
      redirect_to user_path(current_user)
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(entry_params)
      flash[:success] = "Profile updated"
      redirect_to entry_show_path
    else
      flash[:error]
      render 'edit'
    end
  end

  def destroy
    @entry.destroy
    redirect_to root_path
  end

  private
    def entry_params
      params.require(:entry).permit(:title, :body, :image, :user_id, :city_id, :slug)
    end

    def correct_user
      @entry = current_user.entries.find_by(id: params[:id])
      redirect_to root_url if @entry.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      flash[:success] = "Welcome back, #{user.first_name}!"
    else
      flash.now[:danger] = 'Invalid email/password combination' # Displays flash messages on rendered pages
      render 'new'
    end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Vagabond!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :current_city, :password, :password_confirmation, :image, :slug, :business_role, :description)
    end

    #Confirms a logged in user
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end


    def correct_user
      @user = User.friendly.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    #Confirms that user is an admin
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Assigns session to user - logs in
	def log_in (user)
		session[:user_id] = user.id
	end

	#Checks if user is the logged in user
	def current_user?(user)
		user == current_user
	end

	#Confirms user as signed in
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	#Checks if current user is logged in
	def logged_in?
		!current_user.nil?
	end

	#Logs out current user
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/edit.html.erb
<% provide(:button_text, "Save changes") %>

<h1>Update city</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@city) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :photo %>
          <%= f.text_field :photo, class: 'form-control' %>

          <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/cities/index.html.erb
<div class='row'>
  <div class='col-md-offset-1'>

		<% @cities.each do |city| %>
      <%= link_to image_tag(city.photo, class: "city-index-img img-responsive polaroid"), city_show_path(city) %>
      <h4 class='city-name'><%= city.name %></h4><br><br><br>
    <% end %>
  </div>
</div>

app/views/cities/show.html.erb
<div class='row'>
  <h2 class='text-center'>About town in <%= @city.name %></h2>
  <hr>

  <% @city.entries.each do |entry| %>
    <div class='col-md-6 entry-box'>
      <h4><%= link_to entry.title, entry_show_path(entry.id) %></h4>
      <p class='user-entry-p'><%= entry.user.first_name + " " + entry.user.last_name %> | <span>Written <%= time_ago_in_words(entry.created_at) %> ago</span></p>
      <p><%= entry.body.truncate(200) %></p>
    </div>
  <% end %>
</div>

<hr>

app/views/entries/_form.html.erb
<%= form_for @entry, html: { multipart: true } do |f| %>

      <%= f.hidden_field :user_id %>

			<%= f.label :city_id %>
			<%= f.collection_select :city_id, City.order(:name),:id,:name %><br>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %><br>

      <%= f.submit yield(:button_text), class: "btn btn-default" %>
<% end %>

app/views/entries/edit.html.erb
<% provide(:button_text, "Save changes") %>

<h2 class="text-center">Update entry</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

		<%= form_for @entry, url: entry_update_path, method: :patch, html: { multipart: true } do |f| %>

      <%= f.hidden_field :user_id %>

			<%= f.label :city_id %>
			<%= f.collection_select :city_id, City.order(:name),:id,:name, {include_blank: true}, {class: 'form-control'} %>

      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :body %>
      <%= f.text_area :body, class: 'form-control' %><br>

      <%= f.submit yield(:button_text), class: "btn btn-default" %>

		<% end %>

  </div>
</div>

app/views/entries/index.html.erb
<div class='content-container'>
  <h2 class='text-center'>Talk of the Town</h2>
  <hr>
      
      <% @entries.each_with_index do |entry, i| %>
        
        <% if ( i % 4 == 0) %>
        <div class="row entry-big">
          <div class="entry-img col-xs-7">
          <%= image_tag entry.image.url(:medium), class: "img-responsive" %>   
          </div>
          <div class="entry-content col-xs-5">
            <h4><%= link_to entry.title, entry_show_path(entry.id) %></h4>
            <p class='user-entry-p'><%= entry.user.first_name + " " + entry.user.last_name %> | <span><%= entry.created_at.strftime("%m/%d/%Y") %></span></p>
            <p><%= entry.body.truncate(700) %></p>
          </div>
        </div>
        <% else %>
        
          <div class='entry-index-box col-xs-4'>
            <div class="entry-img">
            <%= image_tag entry.image.url(:medium), class: "img-responsive" %>   
            </div>
            <div class="entry-content">
              <h4><%= link_to entry.title, entry_show_path(entry.id) %></h4>
              <p class='user-entry-p'><%= entry.user.first_name + " " + entry.user.last_name %> | <span><%= entry.created_at.strftime("%m/%d/%Y") %></span></p>
              <p><%= entry.body.truncate(200) %></p>
            </div>
          </div>


        <% end %>
      <% end %>
</div>
<%= will_paginate %>

app/views/entries/new.html.erb
<% provide(:button_text, 'Create') %>
<h2 class='text-center'>New Entry</h2>
<hr>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

app/views/entries/show.html.erb
<div class='row'>
  <% if logged_in? && current_user.id == @entry.user.id %>
    <span>
      <%= button_to "Delete", delete_entry_path, method: :delete %>
    </span>
  <% end %>
  <br>
    <%= image_tag @entry.image.url(:large), class: "full-width-img" %>
  <h3><%= @entry.title %></h3>
    <%= image_tag @entry.user.image.url, class: 'thumb' %>

  <h6 class="inline-heading">
    <%= @entry.user.first_name + " " + @entry.user.last_name %> | Written <%= time_ago_in_words(@entry.created_at) %> ago
  </h6>
  <% if logged_in? && current_user.id == @entry.user.id %>
    <span>
      <%= link_to " 🖊 ", edit_entry_path %>
    </span>
  <% end %>
  <hr>
  <p><%= @entry.body %></p>

</div>

app/views/layouts/_carousel.html.erb
  <div class='img-div toggle-image first show'></div>
  <div class='img-div toggle-image second show'></div>
  <div class='img-div toggle-image third show'></div>
  <div class='img-div toggle-image fourth show'></div>
  <div class='img-div toggle-image fifth show'></div>
  <div class='img-div toggle-image sixth show'></div>

app/views/layouts/_footer.html.erb
<footer class="text-center">
	<div class="container">
			<hr>
	<%= image_tag('potato.jpg', :class= => 'potato') %>
	</div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <ul id="login-nav" class="navbar-nav">
      <% if logged_in? %>
      <li class="dropdown pull-right">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= image_tag current_user.image.url, class: 'thumb img-circle' %></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Log in", login_path %> | </li>
      <li><%= link_to "Sign up", signup_path %></li>
      <% end %>
    </ul>
  	<h1 class='text-center'><%= link_to "VAGABOND", root_path %></h1>
    <nav>
      <ul class="nav navbar-nav">
        <li><%= link_to "The Scoop", root_path %></li>
        <li><%= link_to "The Scene", cities_path %></li>
        <li><%= link_to "The Tastemakers", users_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VAGABOND</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Chonburi|Merriweather|Playfair+Display+SC' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <% if current_page?(root_url) %>
      <%= render 'layouts/carousel' %> 
    <% end %>
  	<div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    	<%= yield %>
    

    </div>

    <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <% unless !logged_in? %>
        <%= f.label :image %>
        <%= f.file_field :image, class: 'form-control' %>
      <% end %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :current_city %>
      <%= f.text_field :current_city, class: 'form-control' %>

      <%= f.label :business_role %>
      <%= f.text_field :business_role, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br>

      <%= f.submit yield(:button_text), class: "btn btn-default" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:button_text, "Save changes") %>

<h2 class='text-center'>Update your profile</h2>
<hr>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

  </div>
</div>

app/views/users/index.html.erb
<hr>
  <% @users.each do |user| %>
  <div class='col-md-4 text-center'>
    <%= link_to image_tag(user.image.url(:medium)), user %>
    <div><span><%= link_to user.first_name, user %> | </span><span><%= user.current_city %> | </span><span>Entries: <%= link_to user.entries.count, user %></span></div>
  </div>
  <% end %>
<hr>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:button_text, 'Create my account') %>
<h2 class="text-center">Sign up</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
 <aside class='col-md-5'>
    <ul class='profile-info list-unstyled text-center'>
      <li>
        <%= image_tag @user.image.url(:medium) %>
      </li>
      <li><%= @user.first_name + " " + @user.last_name %></li>
      <li>📍 <%= @user.current_city %></li>
      <li>Member since: <%= @user.created_at.strftime("%m/%d/%Y") %></li>
      <li>Entries posted: <%= @user.entries.count %></li>
      <li>Business Role: <%= @user.business_role %></li>
      <li>Description: <%= @user.description %></li>
    </ul>
  </aside>
  <div class="col-md-7 pull-right">
    <h2>Your entries <%= link_to "➕", new_entry_path %></h2>
    <% @user.entries.each do |entry| %>
      <div class="user-show-entries">
        <h4><%= entry.created_at.strftime("%m/%d/%Y") %> | <%= link_to entry.title, entry_show_path(entry.id) %></h4>
      </div>
    <% end %>
  </div>